### PR TITLE
Updated member.json

### PR DESCRIPTION
**Pull request by mursalfk**
Updated Member.json

### CODE REVIEW

**Comment by viveksharmaui** [comment]
@mursalfk your changed are reviewed and accepted don't forget to rebase and resolve conflicts.

**Comment by mursalfk** [comment]
@viveksharmaui Updated

**Comment by viveksharmaui** [comment]
@mursalfk congratulations your PR is merged.

**Comment by viveksharmaui** [comment]
@all-contributors please add @mursalfk for content

**Pull request merged**
