### PR TITLE
Add Surajv311 to the list of contributors

### PR DESCRIPTION
**Pull request by Surajv311**
@viveksharmaui  @owais4321
Could you please review my P.R ?

### CODE REVIEW

**Review by viveksharmaui — APPROVED** [review]

**Comment by viveksharmaui** [comment]
@Surajv311 congratulations your PR is merged.

**Comment by viveksharmaui** [comment]
@allcontributors please add @Surajv311 for code.

**Comment by Surajv311** [comment]
@viveksharmaui I would like to be a member of the organization. Is there a link from where I can join?

**Comment by slimcoders** [comment]
Hey! @Surajv311 you are most welcome we will add you to our organization then we will invite you in our group.

**Comment by Surajv311** [comment]
@slimcoders Thank you for the info. Btw I haven't received my invitation yet. Could you pls check!

**Comment by slimcoders** [comment]
@Surajv311 please check!

**Comment by Surajv311** [comment]
@slimcoders Checked now. Thank you!

**Pull request merged**
